#!/usr/bin/env python3
"""Spanish for the tool sweep's own prose.

The transcript is generated, so a hand-translated copy would come apart on the
next run. This is the translation the generator reads instead.

Keys are the English strings exactly as they appear in tools/tool-sweep.py. A
missing key falls back to English rather than failing, which keeps the file
readable while it is incomplete and makes the gap visible in the output rather
than hidden behind an empty line.

Only the sweep's own prose lives here. What a tool ANSWERED is never translated:
that is the desktop talking, and a transcript that paraphrases the evidence is
not a transcript.
"""

SECTIONS = {
    "Seeing the desktop": "Ver el escritorio",
    "The catalogue, and the room": "El catálogo y la sala",
    "Taking the controls": "Tomar los controles",
    "Pointer and keyboard": "Puntero y teclado",
    "Clipboard": "Portapapeles",
    "Windows and desktops": "Ventanas y escritorios",
    "The accessibility tree": "El árbol de accesibilidad",
    "Terminal": "Terminal",
    "Browser, over DevTools": "Navegador, por DevTools",
    "Files": "Archivos",
    "Audio": "Audio",
    "Recording and re-streaming": "Grabación y retransmisión",
    "Gamepad": "Joystick",
    "Persistent shells": "Shells persistentes",
    "Packages and services": "Paquetes y servicios",
    "SSH": "SSH",
    "Snapshots": "Snapshots",
    "System": "Sistema",
    "Macro actions": "Acciones compuestas",
    "Handing back": "Devolver el control",
    "Not covered by the sweep": "Sin cubrir por el barrido",
}

STATUS = {
    "ok": "ok",
    "degraded — the environment explains it": "degradado — lo explica el entorno",
    "not run": "no ejecutada",
    "FAILED": "FALLÓ",
}

HEADER = {
    "SentinelDesk — every tool called against a real desktop":
        "SentinelDesk — cada herramienta llamada contra un escritorio real",
    "Run on {when} against {version}":
        "Ejecutado el {when} contra {version}",
    "Generated by tools/tool-sweep.py. The summary table, with the same":
        "Generado por tools/tool-sweep.py. La tabla resumen, con la misma",
    "numbering, is in docs/tool-sweep.md.":
        "numeración, está en docs/tool-sweep.md.",
    "Result is the tool's reply verbatim. `not run` blocks say why instead.":
        "Result es la respuesta textual de la herramienta. Los bloques `no "
        "ejecutada` dicen el motivo en su lugar.",
    "Arguments sent": "Argumentos enviados",
    "Summary:": "Qué hizo:",
    "Method score": "Puntaje del método",
    "To take it further:": "Cómo llevarla más lejos:",
    "Review: not yet reviewed.": "Reseña: todavía sin reseñar.",
    "none": "ninguno",
    "(no output)": "(sin salida)",
    "no reason recorded": "sin motivo registrado",
    "note": "nota",
}

TEXT = {
    # --- what each call was for ---------------------------------------------
    "Resolution, session and what the desktop is running":
        "Resolución, sesión y qué está corriendo el escritorio",
    "Screen geometry and how many virtual desktops there are":
        "Geometría de la pantalla y cuántos escritorios virtuales hay",
    "Capture the whole screen as a PNG": "Capturar la pantalla entera como PNG",
    "Capture one rectangle instead of the whole screen":
        "Capturar un rectángulo en vez de la pantalla entera",
    "The colour of one pixel, to assert state without an image":
        "El color de un pixel, para verificar estado sin traer una imagen",
    "OCR the screen into text": "Pasar la pantalla a texto con OCR",
    "OCR, but return where a string is so it can be clicked":
        "OCR, pero devolviendo dónde está un texto para poder clickearlo",
    "Where the pointer is now": "Dónde está el puntero ahora",
    "Which window has focus": "Qué ventana tiene el foco",
    "Every open window with its id and geometry":
        "Cada ventana abierta con su id y su geometría",
    "The virtual desktops and which one is current":
        "Los escritorios virtuales y cuál es el actual",
    "Running processes": "Procesos corriendo",
    "Whether a named process is alive": "Si un proceso con ese nombre está vivo",
    "Applications with a desktop entry": "Aplicaciones con entrada de escritorio",
    "Sink, volume and whether it is muted": "Sink, volumen y si está silenciado",
    "Any error dialog or alert currently on screen":
        "Cualquier diálogo de error o alerta que haya en pantalla",
    "Sleep, to let the interface settle":
        "Dormir, para dejar que la interfaz se asiente",
    "Wait until the screen stops changing and the CPU settles":
        "Esperar a que la pantalla deje de cambiar y la CPU se calme",

    "Find tools from a plain-words description of a task":
        "Encontrar herramientas a partir de una tarea descrita en palabras",
    "The audit trail: every call with its connection and result":
        "La auditoría: cada llamada con su conexión y su resultado",
    "Who is in the room, who is driving, may this connection act":
        "Quién está en la sala, quién maneja, y si esta conexión puede actuar",
    "Ask the room for the desktop before touching it":
        "Pedirle el escritorio a la sala antes de tocarlo",
    "Give the desktop back to the people watching":
        "Devolverle el escritorio a quienes están mirando",
    "Give the desktop back": "Devolver el escritorio",

    "Move the pointer to an absolute position":
        "Mover el puntero a una posición absoluta",
    "Move the pointer": "Mover el puntero",
    "Click, optionally moving there first":
        "Hacer clic, opcionalmente moviéndose ahí primero",
    "Click a button": "Hacer clic con un botón",
    "Press a button and hold it": "Apretar un botón y mantenerlo",
    "Press and hold": "Apretar y mantener",
    "Release the held button": "Soltar el botón que estaba apretado",
    "Release": "Soltar",
    "Drag from one point to another": "Arrastrar de un punto a otro",
    "Drag between two points": "Arrastrar entre dos puntos",
    "Scroll the wheel": "Mover la rueda",
    "Type a string into whatever has focus":
        "Escribir un texto en lo que tenga el foco",
    "Type a string": "Escribir un texto",
    "Press a key or combination by X keysym name":
        "Apretar una tecla o combinación por su nombre de keysym de X",
    "Press a key combination": "Apretar una combinación de teclas",

    "Put text on the X clipboard": "Poner texto en el portapapeles de X",
    "Read the X clipboard back": "Leer el portapapeles de X",

    "Start a program on the desktop, detached":
        "Arrancar un programa en el escritorio, desacoplado",
    "Wait until a window matching a title appears":
        "Esperar a que aparezca una ventana cuyo título coincida",
    "List windows, to find the one just opened":
        "Listar ventanas, para encontrar la que se acaba de abrir",
    "Focus and raise a window by id": "Enfocar y traer al frente una ventana por id",
    "Focus and raise a window": "Enfocar y traer al frente una ventana",
    "The raw X properties of one window":
        "Las propiedades X crudas de una ventana",
    "Raw X properties": "Propiedades X crudas",
    "The raw X window tree, parents and children":
        "El árbol de ventanas de X, padres e hijos",
    "The raw X window tree": "El árbol de ventanas de X",
    "Move a window to a position": "Mover una ventana a una posición",
    "Move a window": "Mover una ventana",
    "Resize a window": "Redimensionar una ventana",
    "Minimise a window": "Minimizar una ventana",
    "Minimise": "Minimizar",
    "Restore a minimised window": "Restaurar una ventana minimizada",
    "Restore": "Restaurar",
    "Maximise a window": "Maximizar una ventana",
    "Maximise": "Maximizar",
    "Put a window full screen": "Poner una ventana en pantalla completa",
    "Full screen": "Pantalla completa",
    "Change an EWMH state such as 'above'":
        "Cambiar un estado EWMH como 'above'",
    "Set an EWMH state": "Fijar un estado EWMH",
    "Send a window to a virtual desktop":
        "Mandar una ventana a un escritorio virtual",
    "Send a window to another desktop": "Mandar una ventana a otro escritorio",
    "Switch to another virtual desktop": "Cambiar a otro escritorio virtual",
    "Switch virtual desktop": "Cambiar de escritorio virtual",
    "Close the window the sweep opened":
        "Cerrar la ventana que abrió el barrido",
    "Close a window": "Cerrar una ventana",

    "Read the desktop as structure rather than pixels":
        "Leer el escritorio como estructura en vez de como píxeles",
    "Find elements by role, name or text":
        "Encontrar elementos por rol, nombre o texto",
    "Find the editable fields, to write into one by ref":
        "Encontrar los campos editables, para escribir en uno por ref",
    "Wait until a matching element exists":
        "Esperar a que exista un elemento que coincida",
    "Only what changed in the tree since the last call":
        "Sólo lo que cambió en el árbol desde la última llamada",
    "Read an element's text by ref, without OCR":
        "Leer el texto de un elemento por ref, sin OCR",
    "Read an element's text by ref": "Leer el texto de un elemento por ref",
    "Give an editable field keyboard focus":
        "Darle el foco del teclado a un campo editable",
    "Give an element keyboard focus": "Darle el foco del teclado a un elemento",
    "Invoke an element's action directly, no pointer involved":
        "Invocar la acción de un elemento directamente, sin usar el puntero",
    "Invoke an element's action directly":
        "Invocar la acción de un elemento directamente",
    "Write text straight into a field by ref, no typing":
        "Escribir directo en un campo por ref, sin tipear",
    "Write into a field by ref": "Escribir en un campo por ref",

    "Open a terminal window a person can watch":
        "Abrir una terminal que una persona pueda mirar",
    "Type a command into that terminal and wait for the prompt":
        "Tipear un comando en esa terminal y esperar el prompt",
    "Read back what the terminal shows": "Leer lo que muestra la terminal",

    "Start Chromium with DevTools and wait for it to answer":
        "Arrancar Chromium con DevTools y esperar a que responda",
    "Wait for a CSS selector to exist": "Esperar a que exista un selector CSS",
    "List the open tabs": "Listar las pestañas abiertas",
    "Navigate the current tab": "Navegar en la pestaña actual",
    "Read the page's visible text": "Leer el texto visible de la página",
    "Type into a field by selector": "Escribir en un campo por selector",
    "Click an element by selector": "Hacer clic en un elemento por selector",
    "Evaluate JavaScript against the real DOM":
        "Evaluar JavaScript contra el DOM real",

    "Write a file, optionally as root":
        "Escribir un archivo, opcionalmente como root",
    "Read a file back": "Leer el archivo de vuelta",
    "List a directory": "Listar un directorio",

    "Set the volume, or mute": "Fijar el volumen, o silenciar",
    "Read the volume and mute state back":
        "Leer de vuelta el volumen y el estado de silencio",

    "Record the screen to a file alongside the live stream":
        "Grabar la pantalla a un archivo en paralelo al stream en vivo",
    "Whether a recording is running, and how big it is":
        "Si hay una grabación corriendo, y cuánto pesa",
    "Let the recording collect a second of video":
        "Dejar que la grabación junte un segundo de video",
    "Stop and finalise the file": "Parar y cerrar el archivo correctamente",
    "The recordings on disk": "Las grabaciones que hay en disco",
    "Send the live encode to an external destination":
        "Mandar el encode en vivo a un destino externo",
    "Where the desktop is currently being published":
        "Dónde se está publicando el escritorio ahora",
    "Stop publishing": "Dejar de publicar",

    "Hold or release a button by W3C index":
        "Apretar o soltar un botón por índice W3C",
    "Press a gamepad button": "Apretar un botón del joystick",
    "Press and release a button": "Apretar y soltar un botón",
    "Tap a button for a moment": "Tocar un botón por un instante",
    "Move one stick axis": "Mover un eje del stick",
    "Move a stick": "Mover un stick",
    "Set every button and axis in one call":
        "Fijar todos los botones y ejes en una sola llamada",
    "Set the whole pad at once": "Fijar el joystick entero de una vez",

    "Start a shell session that survives between calls":
        "Abrir una sesión de shell que sobrevive entre llamadas",
    "Run a command in that session and wait for it":
        "Correr un comando en esa sesión y esperarlo",
    "Run a command in a session": "Correr un comando en una sesión",
    "Send raw keystrokes, without waiting":
        "Mandar teclas crudas, sin esperar",
    "Send keystrokes to a session": "Mandar teclas a una sesión",
    "Give the shell a moment to produce output":
        "Darle un momento a la shell para que produzca salida",
    "Read and clear what the session has produced":
        "Leer y limpiar lo que produjo la sesión",
    "Read a session's new output": "Leer la salida nueva de una sesión",
    "The open shell sessions": "Las sesiones de shell abiertas",
    "End the session": "Terminar la sesión",

    "Run a shell command and return stdout, stderr and exit code":
        "Correr un comando de shell y devolver stdout, stderr y código de salida",
    "Whether passwordless sudo is available in this image":
        "Si esta imagen tiene sudo sin contraseña",
    "Search apt without installing anything":
        "Buscar en apt sin instalar nada",
    "Ask supervisord about the desktop's services":
        "Preguntarle a supervisord por los servicios del escritorio",
    "Install a package with apt, reporting progress":
        "Instalar un paquete con apt, reportando progreso",
    "Install packages with apt": "Instalar paquetes con apt",
    "Remove the package the sweep installed":
        "Sacar el paquete que instaló el barrido",
    "Remove packages with apt": "Sacar paquetes con apt",

    "Generate a key pair for the desktop's user":
        "Generar un par de claves para el usuario del escritorio",
    "The open SSH sessions": "Las sesiones SSH abiertas",
    "Open an SSH session to a host": "Abrir una sesión SSH contra un host",
    "Open an SSH session": "Abrir una sesión SSH",
    "Run a command on the remote host":
        "Correr un comando en el host remoto",
    "Run a command over SSH": "Correr un comando por SSH",
    "Send a file over SFTP": "Mandar un archivo por SFTP",
    "Fetch a file over SFTP": "Traer un archivo por SFTP",
    "List a directory on the remote host":
        "Listar un directorio en el host remoto",
    "List a remote directory": "Listar un directorio remoto",
    "Forward a local port to the remote side":
        "Reenviar un puerto local hacia el lado remoto",
    "Forward a remote port back to here":
        "Reenviar un puerto remoto de vuelta hacia acá",
    "The tunnels open on this session":
        "Los túneles abiertos en esta sesión",
    "The tunnels on a session": "Los túneles de una sesión",
    "Close one tunnel by id": "Cerrar un túnel por id",
    "Close one tunnel": "Cerrar un túnel",
    "Install the public key on the remote host":
        "Instalar la clave pública en el host remoto",
    "Install a public key on the remote host":
        "Instalar una clave pública en el host remoto",
    "End the SSH session": "Terminar la sesión SSH",

    "A restore point: the home plus the installed package list":
        "Un punto de restauración: el home más la lista de paquetes instalados",
    "The snapshots on disk": "Los snapshots que hay en disco",
    "Roll the home back to a snapshot":
        "Volver el home al estado de un snapshot",
    "Delete a snapshot": "Borrar un snapshot",

    "Change the resolution without restarting anything":
        "Cambiar la resolución sin reiniciar nada",
    "Confirm the new geometry": "Confirmar la geometría nueva",
    "Put the resolution back": "Volver la resolución a como estaba",
    "Launch, wait for the window, focus it, in one call":
        "Lanzar, esperar la ventana y enfocarla, en una sola llamada",
    "Kill a process the sweep started, by name":
        "Matar por nombre un proceso que arrancó el barrido",

    "Fill several fields by accessible name and submit":
        "Completar varios campos por nombre accesible y enviar",
    "Fill several fields by accessible name":
        "Completar varios campos por nombre accesible",

    # --- reasons a step did not run -----------------------------------------
    "the room did not grant control": "la sala no concedió el control",
    "the test window did not open": "no se abrió la ventana de prueba",
    "nothing was on screen to address":
        "no había nada en pantalla a lo que dirigirse",
    "no editable element was on screen":
        "no había ningún elemento editable en pantalla",
    "no shell session could be opened":
        "no se pudo abrir ninguna sesión de shell",
    "no SSH server reachable in the container":
        "no hay un servidor SSH alcanzable en el contenedor",
    "the SSH session did not open": "no se abrió la sesión SSH",
    "no tunnel id came back": "no volvió ningún id de túnel",
    "nothing was installed to remove": "no se instaló nada para sacar",
    "--skip-packages was given": "se pasó --skip-packages",
    "control was never granted": "nunca se concedió el control",
    "no step in the sweep calls this":
        "ningún paso del barrido llama a esta herramienta",
    "it would overwrite the live home directory; the only tool the sweep "
    "cannot make safe against something it created":
        "sobrescribiría el home real; la única herramienta que el barrido no "
        "puede hacer segura contra algo creado por él mismo",

    # --- notes attached to a degraded result ---------------------------------
    "Chromium exposes the entry as editable but implements no "
    "AT-SPI EditableText on it — use browser_type inside a page":
        "Chromium expone el campo como editable pero no implementa EditableText "
        "de AT-SPI sobre él — dentro de una página va browser_type",
    "same AT-SPI limitation as ui_set_text: fill_form writes "
    "through the same interface":
        "misma limitación de AT-SPI que ui_set_text: fill_form escribe por la "
        "misma interfaz",
}


# Month names, because a Spanish transcript dated "06 August 2026" is a
# translation that stopped one line short.
MONTHS = {
    "January": "enero", "February": "febrero", "March": "marzo",
    "April": "abril", "May": "mayo", "June": "junio", "July": "julio",
    "August": "agosto", "September": "septiembre", "October": "octubre",
    "November": "noviembre", "December": "diciembre",
}


def date(when):
    """'06 August 2026, 14:03' -> '06 de agosto de 2026, 14:03'."""
    for en, es in MONTHS.items():
        if en in when:
            return when.replace(f" {en} ", f" de {es} de ")
    return when


def t(text, table=None):
    """Translate one string, falling back to the English when it is missing."""
    if not text:
        return text
    for source in (table,) if table else (TEXT, SECTIONS, HEADER, STATUS):
        if source and text in source:
            return source[text]
    return text
