#!/bin/sh
#
# SentinelDesk
# A collaborative operating system for people and AI agents.
#
# Copyright 2026 Federico Pereira <fpereira@cnsoluciones.com>
# Co-authored by Nicolas Pereira <npereira@cnsoluciones.com>
#
# Licensed under the Apache License, Version 2.0.
#
# This product's name and logo are trademarks of Federico Pereira and are not
# covered by the license above. See the README for the trademark policy.
#
# SPDX-License-Identifier: Apache-2.0

# Publishes the desktop's own user guide on the project site.
#
# The guide already lives in internal/webui/assets/docs/, where the binary
# embeds it and serves it at /docs/ on a running instance. GitHub Pages serves
# this repository from its root, so those same files are already reachable — but
# they are written for the container, where the guide sits at the absolute path
# /docs/. Under Pages the site lives beneath /sentineldesk/, so every one of
# those absolute paths resolves against the wrong root and the guide loads
# unstyled with no content.
#
# This copies the guide into docs/guide/ and rewrites exactly those paths to be
# relative. The copy is a BUILD ARTEFACT, not a fork: never edit docs/guide/ by
# hand — edit internal/webui/assets/docs/ and run this again.
#
#     ./docs/sync-guide.sh
#
# Why a copy rather than making the originals relative: relative paths would in
# fact work in both places, but that means editing files the binary embeds and
# serves, and the only way to prove that change is safe is to build the image
# and load the desktop. A copy touches nothing that ships.

set -eu

root=$(cd "$(dirname "$0")/.." && pwd)
src="$root/internal/webui/assets/docs"
dst="$root/docs/guide"

[ -d "$src" ] || { echo "✗ no encuentro la guía en $src"; exit 1; }

# `sed -i` is not portable: GNU takes -i alone, BSD/macOS wants a backup suffix.
# Redirect and move behaves the same on both.
rewrite() {
  f=$1; shift
  sed "$@" "$f" > "$f.tmp" && mv "$f.tmp" "$f"
}

rm -rf "$dst"
mkdir -p "$dst/content"
cp "$src/index.html" "$src/docs.css" "$src/docs.js" "$dst/"
cp "$src"/content/*.html "$dst/content/"

ICON="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect x='4' y='8' width='56' height='38' rx='6' fill='%233FD68C'/%3E%3Crect x='10' y='14' width='44' height='26' rx='2' fill='%230C0E0D'/%3E%3Crect x='22' y='50' width='20' height='4' rx='2' fill='%233FD68C'/%3E%3Crect x='16' y='54' width='32' height='4' rx='2' fill='%232AA96C'/%3E%3C/svg%3E"

# The stylesheet, the script and the favicon. Relative to the guide's own
# directory, which is where all three sit.
rewrite "$dst/index.html" \
  -e 's|href="/docs/docs.css"|href="docs.css"|' \
  -e 's|src="/docs/docs.js"|src="docs.js"|' \
  -e "s|href=\"/favicon.ico\"|href=\"$ICON\"|"

# "Back to the desktop" pointed at /, which on a running instance is the
# desktop. Here there is no desktop to go back to, so both links go to the
# project site's landing page instead.
rewrite "$dst/index.html" -e 's|href="/"|href="../index.html"|g'

# The language fragments are fetched at runtime from an absolute path too.
rewrite "$dst/docs.js" -e "s|fetch('/docs/content/'|fetch('content/'|"

# …and the label has to stop promising a desktop that is not there.
rewrite "$dst/docs.js" \
  -e "s|'← Back to the desktop'|'← Back to the project site'|" \
  -e "s|'← Volver al escritorio'|'← Volver al sitio del proyecto'|" \
  -e "s|'← Voltar para a área de trabalho'|'← Voltar ao site do projeto'|"

# A marker, so nobody edits the copy thinking it is the source.
for f in "$dst/index.html" "$dst/docs.js" "$dst/docs.css"; do
  case "$f" in
    *.html) open='<!-- ' ; close=' -->' ;;
    *)      open='/* '   ; close=' */'  ;;
  esac
  printf '%sGenerated by docs/sync-guide.sh from internal/webui/assets/docs/ — do not edit.%s\n' "$open" "$close" > "$f.hdr"
  cat "$f" >> "$f.hdr" && mv "$f.hdr" "$f"
done

echo "✓ guía publicada en docs/guide/ ($(find "$dst" -type f | wc -l | tr -d ' ') archivos)"
echo "  rutas absolutas reescritas: docs.css · docs.js · favicon · content/ · enlaces de vuelta"
